// common 公共
export const COM_NAV_STATUS = 'COM_NAV_STATUS'
export const COM_TABBAR_STATUS = 'COM_TABBAR_STATUS'
export const COM_HEADER_STATUS = 'COM_HEADER_STATUS'
export const COM_LOADING_STATUS = 'COM_LOADING_STATUS'
export const CHANGE_CURRENT_THEME_ID = 'CHANGE_CURRENT_THEME_ID'
export const SET_AVATAR_IMG = 'SET_AVATAR_IMG'

// user 用户
export const SET_USER_TOKEN = 'SET_USER_TOKEN'
export const SET_USER_INFO = 'SET_USER_INFO'
export const SET_LOGIN_STATUS = 'SET_LOGIN_STATUS'
export const GET_USER_DATA = 'GET_USER_DATA'

// artwork 作品
export const SET_ARTWORK_LIST = 'SET_ARTWORK_LIST'
export const SET_PAGE_NUM = 'SET_PAGE_NUM'
export const SET_CURRENT_PAGE = 'SET_CURRENT_PAGE'
export const SET_DATA_STATUS = 'SET_DATA_STATUS'
export const SET_ARTWORK_DETAIL = 'SET_ARTWORK_DETAIL'
export const RESET_ARTWORKS_DATA = 'RESET_ARTWORKS_DATA'
export const UNSHIFT_ARTWORKS_DATA = 'UNSHIFT_ARTWORKS_DATA'
export const CONCAT_ARTWORKS_DATA = 'CONCAT_ARTWORKS_DATA'
export const SET_LAST_TIME = 'SET_LAST_TIME'
export const SET_NEXT_TIME = 'SET_NEXT_TIME'

// uploader
export const SET_IMG_UPLOAD_CACHE = 'SET_IMG_UPLOAD_CACHE'
export const SET_IMG_PATHS = 'SET_IMG_PATHS'
export const SET_IMG_STATUS = 'SET_IMG_STATUS'
export const SET_PROGRESS_VALUE = 'SET_PROGRESS_VALUE'
export const SET_VIDEO_PATHS = 'SET_VIDEO_PATHS'
